# SPDX-License-Identifier: Apache-2.0
[package]
name = "rustic-file-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
[lints]
workspace = true
[dependencies]
rustic-abi = { path = "../abi" }
rustic-fs = { path = "../fs" }
sha2.workspace = true
