# SPDX-License-Identifier: Apache-2.0
[package]
name = "rustic-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
boot-image = ["dep:limine"]

[target.'cfg(target_os = "none")'.dependencies]
limine = { version = "=0.5.0", optional = true }

[[bin]]
name = "rustic-os"
path = "src/main.rs"
required-features = ["boot-image"]
test = false
bench = false
