# SPDX-License-Identifier: Apache-2.0
[package]
name = "rustic-file-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
[lints]
workspace = true
[features]
native = []
[dependencies]
rustic-sdk = { path = "../../crates/sdk" }
rustic-fs = {path="../../crates/fs"}
rustic-file-service = {path="../../crates/file-service"}
[[bin]]
name = "file-server"
path = "src/main.rs"
required-features = ["native"]
test = false
bench = false
